version: "3.2"

networks:
  test_network2:
    driver: bridge

volumes:
  test_volume2:
    driver: local
  grafana_storage:
    driver: local
  mongodb_storage:
    driver: local
  influxdb_storage:
    driver: local


services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - test_network2
    restart: on-failure:5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
     - test_network2
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_storage
        target: /data/
    restart: on-failure:5

  mongodb2:
    image: mongo:latest
    container_name: mongodb_cloud
    networks:
     - test_network2
    ports:
      - "27016:27017"
    volumes:
      - type: volume
        source: mongodb_storage
        target: /data/
    restart: on-failure:5


  test_container2:
    image: ubuntu
    networks:
     - test_network2
    volumes:
     - test_volume2:/testvolume2_path
     - grafana_storage:/grafana_storage_path
     - influxdb_storage:/influxdb_storage_path
     - mongodb_storage:/mongodb_storage_path
    container_name: test2
    restart: on-failure:5
    command: tail -f /dev/null

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    networks:
     - test_network2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.4.3
    container_name: kafka_server
    depends_on:
      - zookeeper
    ports:
     - 9094:9094
    networks:
     - test_network2
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LOG_DIRS: /kafka/logsver
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'